title: SIVA GANESH
logo: /assets/img/p1.png
show_downloads: true
descroption: H
theme: jekyll-theme-minimal

# remote_theme: chrisrhymes/bulma-clean-theme
#google_analytics: G-S191BDS1TY
# theme_color: '#9d7d2a'
# show_sidebar: true  # by default shows latest posts
# _includes/latest-posts.html  # to show different content instead of latest posts

# theme: just-the-docs
